# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
dockers:
  - skip_push: auto
    image_templates:
      - "forge.pnyhf.eu/l-x/woodpecker-ntfy:{{ .Tag }}"
      - "forge.pnyhf.eu/l-x/woodpecker-ntfy:{{ .Major }}"
      - "forge.pnyhf.eu/l-x/woodpecker-ntfy:latest"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--platform=linux/arm64"
gitea_urls:
  api: https://forge.pnyhf.eu/api/v1
  download: https://forge.pnyhf.eu
env_files:
  gitea_token: .forgejo_token
