when:
    event: [push, pull_request]
pipeline:
    test:
        image: golang:1.20.3
        group: test
        commands:
            - go build
            - go test -coverprofile cover.out -v
            - go tool cover -func cover.out
    ntfy:
        image: codeberg.org/l-x/woodpecker-ntfy:latest
        pull: true
        settings:
            tags: robot,memo,${CI_BUILD_EVENT},${CI_REPO_NAME}
            message: >
                Commit by ${CI_COMMIT_AUTHOR} on ${CI_COMMIT_BRANCH}:

                ${CI_COMMIT_MESSAGE}
            click: ${CI_BUILD_LINK}
