pipeline:
    test:
        image: golang:1.20.3
        group: test
        commands:
            - go build
            - go test
    ntfy:
        image: codeberg.org/l-x/woodpecker-ntfy:latest
        pull: true
        settings:
            tags: robot,${CI_BUILD_EVENT},${CI_REPO_NAME}
            message: >
                📝 Commit by ${CI_COMMIT_AUTHOR} on ${CI_COMMIT_BRANCH}:

                ${CI_COMMIT_MESSAGE}
            click: ${CI_BUILD_LINK}