variables:
    - &golang_image 'golang:1.20.2'

pipeline:
    lint-pipeline:
        image: *golang_image
        commands:
            - go run github.com/woodpecker-ci/woodpecker/cmd/cli lint
    test:
        image: *golang_image
        group: test
        commands:
            - go test
