when:
  branch: ${CI_REPO_DEFAULT_BRANCH}
pipeline:
  publish stable:
    when:
      event: tag
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64
      repo: codeberg.org/${CI_REPO_OWNER}/woodpecker-ntfy
      registry: codeberg.org
      tags: latest
      dry-run: true
      username: ${CI_REPO_OWNER}
      password:
        from_secret: gitea_token

  publish next:
    when:
      event: push
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64
      repo: codeberg.org/${CI_REPO_OWNER}/woodpecker-ntfy
      registry: codeberg.org
      tags: next
      username: ${CI_REPO_OWNER}
      password:
        from_secret: gitea_token