when:
  branch: ${CI_REPO_DEFAULT_BRANCH}
pipeline:
  publish:
    when:
      event: tag
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: codeberg.org/${CI_REPO_OWNER}/woodpecker-ntfy
      registry: codeberg.org
      tags: latest
      auto_tag: true
      username: ${CI_REPO_OWNER}
      password:
        from_secret: gitea_token
