when:
  event: [push, pull_request]
pipeline:
  tests:
    image: golang:1.20.3
    group: test
    commands:
      - go build
      - go test . plugin
  notify success:
    when:
      status: success
    image: codeberg.org/l-x/woodpecker-ntfy
    settings:
      url: https://push.pnyhf.eu/woodpecker-ntfy
      token:
        from_secret: ntfy
      tags: computer,tada,${CI_BUILD_EVENT}
      title: Tests for ${CI_REPO} succeeded
      message: >
        Author: ${CI_COMMIT_AUTHOR}
        Branch: ${CI_COMMIT_BRANCH}
        Commit message: ${CI_COMMIT_MESSAGE}}
        ${CI_SYSTEM_LINK}
  notify failure:
    when:
      status: failure
    image: codeberg.org/l-x/woodpecker-ntfy
    settings:
      url: https://push.pnyhf.eu/woodpecker-ntfy
      token:
        from_secret: ntfy
      priority: urgent
      tags: computer,rotating_light,skull,${CI_BUILD_EVENT}
      title: Tests for ${CI_REPO} failed
      message: >
        Author: ${CI_COMMIT_AUTHOR}
        Branch: ${CI_COMMIT_BRANCH}
        Commit message: ${CI_COMMIT_MESSAGE}}
        ${CI_SYSTEM_LINK}


