when:
  event: [push, pull_request]
pipeline:
  tests:
    image: golang:1.20.3
    group: test
    commands:
      - go build
      - go test . plugin
  notify success:
    when:
      status: success
    image: codeberg.org/l-x/woodpecker-ntfy
    settings:
      url: https://push.pnyhf.eu/woodpecker-ntfy
      token:
        from_secret: ntfy
      tags: computer,tada
      title: Tests for ${CI_REPO_NAME} succeeded (${CI_BUILD_STATUS})
  notify failure:
    when:
      status: failure
    image: codeberg.org/l-x/woodpecker-ntfy
    settings:
      url: https://push.pnyhf.eu/woodpecker-ntfy
      token:
        from_secret: ntfy
      priority: urgent
      tags: computer,rotating_light,skull
      title: Tests for ${CI_REPO_NAME} failed (${CI_BUILD_STATUS})
