when:
  event: [push, pull_request]
pipeline:
  tests:
    image: golang:1.20.3
    group: test
    commands:
      - go build
      - go test
  notify success:
    when:
      status: success
    image: codeberg.org/l-x/woodpecker-ntfy
    settings:
      url: https://push.pnyhf.eu/woodpecker-ntfy
      token:
        from_secret: ntfy
  notify failure:
    when:
      status: failure
    image: codeberg.org/l-x/woodpecker-ntfy
    settings:
      url: https://push.pnyhf.eu/woodpecker-ntfy
      token:
        from_secret: ntfy