variables:
  - &golang_image 'golang:1.21.0'
  - &ntfy_image 'codeberg.org/l-x/woodpecker-ntfy:latest'
  - &ntfy_url 'https://push.pnyhf.eu/woodpecker-ntfy'
  
when:
  event: push
pipeline:
  tests:
    image: *golang_image
    group: test
    commands:
      - go build
      - go test -v ./*.go
      - go test -v plugin/*.go
  notify success:
    when:
      status: success
    image: *ntfy_image
    settings:
      url: *ntfy_url
      token:
        from_secret: ntfy
      tags: ${CI_BUILD_EVENT},${CI_REPO_NAME},tada
      title: Tests for ${CI_REPO} succeeded
      message: |
        Author: ${CI_COMMIT_AUTHOR}
        Branch: ${CI_COMMIT_BRANCH}
        Commit message: ${CI_COMMIT_MESSAGE}
  notify failure:
    when:
      status: failure
    image: *ntfy_image
    settings:
      url: *ntfy_url
      token:
        from_secret: ntfy
      priority: urgent
      tags: ${CI_BUILD_EVENT},${CI_REPO_NAME},skull
      title: Tests for ${CI_REPO} failed
      message: |
        Author: ${CI_COMMIT_AUTHOR}
        Branch: ${CI_COMMIT_BRANCH}
        Commit message: ${CI_COMMIT_MESSAGE}
