when:
  event: push
  branch: ${CI_REPO_DEFAULT_BRANCH}

pipeline:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: codeberg.org/${CI_REPO_OWNER}/woodpecker-ntfy
      registry: codeberg.org
      tag: next
      platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64
      auto_tag: false
      username: ${CI_REPO_OWNER}
      password:
        from_secret: gitea_token