when:
  event: tag
  branch: ${CI_REPO_DEFAULT_BRANCH}
steps:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: codeberg.org/${CI_REPO_OWNER}/woodpecker-ntfy
      registry: codeberg.org
      tags: latest
      auto_tag: true
      platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64
      username: ${CI_REPO_OWNER}
      password:
        from_secret: gitea_token
